# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3f2ba594422eae2e5ab6a056e61cef8872a34e38dda757ac14017a4e11c239cb1883d1cda7c2d5b822b29ec180bf2578af788e0c52498cfdc7b074047d168d

test:
  secret_key_base: 20174e8c98c7ca93ae0a64b1e8df68023faabface7a9c21fc1f34187b30d96ee634f78bf8684ed51ad28d2559fcf9f179c1fda49ba7f5c922907045c9b46e444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
